export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',

  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_REFRESH_MISSING: 'AUTH_REFRESH_MISSING',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',

  DB_UNIQUE_CONSTRAINT: 'DB_UNIQUE_CONSTRAINT',
  DB_NOT_FOUND: 'DB_NOT_FOUND',
  DB_CONSTRAINT: 'DB_CONSTRAINT',

  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_FAILED: 'JOB_FAILED',

  // Wallet related errors
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_DISABLED: 'WALLET_DISABLED',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  AMOUNT_INVALID: 'AMOUNT_INVALID',

  // System/Concurrency errors
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  SYSTEM_WALLET_NOT_FOUND: 'SYSTEM_WALLET_NOT_FOUND',
  LEDGER_TX_NOT_FOUND: 'LEDGER_TX_NOT_FOUND',

  INVALID_CURSOR: 'INVALID_CURSOR',
} as const;
