export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',

  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_REFRESH_MISSING: 'AUTH_REFRESH_MISSING',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',

  DB_UNIQUE_CONSTRAINT: 'DB_UNIQUE_CONSTRAINT',
  DB_NOT_FOUND: 'DB_NOT_FOUND',
  DB_CONSTRAINT: 'DB_CONSTRAINT',

  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_FAILED: 'JOB_FAILED',

  // Wallet related errors
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_DISABLED: 'WALLET_DISABLED',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  AMOUNT_INVALID: 'AMOUNT_INVALID',

  // System/Concurrency errors
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  SYSTEM_USER_NOT_FOUND: 'SYSTEM_USER_NOT_FOUND',
  SYSTEM_WALLET_NOT_FOUND: 'SYSTEM_WALLET_NOT_FOUND',
  LEDGER_TX_NOT_FOUND: 'LEDGER_TX_NOT_FOUND',

  INVALID_CURSOR: 'INVALID_CURSOR',

  // Payment domain
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_INVALID_STATE: 'PAYMENT_INVALID_STATE',
  PAYMENT_ALREADY_CAPTURED: 'PAYMENT_ALREADY_CAPTURED',
  PAYMENT_ALREADY_CANCELED: 'PAYMENT_ALREADY_CANCELED',
  PAYMENT_ALREADY_REFUNDED: 'PAYMENT_ALREADY_REFUNDED',
  PAYMENT_REFUND_NOT_ALLOWED: 'PAYMENT_REFUND_NOT_ALLOWED',

  HOLD_NOT_FOUND: 'HOLD_NOT_FOUND',
  HOLD_EXPIRED: 'HOLD_EXPIRED',

  INSUFFICIENT_AVAILABLE_FUNDS: 'INSUFFICIENT_AVAILABLE_FUNDS',

  WEBHOOK_ENDPOINT_NOT_FOUND: 'WEBHOOK_ENDPOINT_NOT_FOUND',
  WEBHOOK_ENDPOINT_INVALID_CONFIG: 'WEBHOOK_ENDPOINT_INVALID_CONFIG',
  WEBHOOK_SOURCE_UNSUPPORTED: 'WEBHOOK_SOURCE_UNSUPPORTED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  INBOX_MESSAGE_NOT_FOUND: 'INBOX_MESSAGE_NOT_FOUND',
  INBOX_MESSAGE_DUPLICATE: 'INBOX_MESSAGE_DUPLICATE',
} as const;
