export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_REFRESH_MISSING: "AUTH_REFRESH_MISSING",
  AUTH_REFRESH_INVALID: "AUTH_REFRESH_INVALID",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  WALLET_DISABLED: "WALLET_DISABLED",
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  LEDGER_TX_NOT_FOUND: "LEDGER_TX_NOT_FOUND",
} as const;
